<?php

namespace Tests\Feature\Services;

use App\Models\Phone;
use App\Services\PhoneServices;
use Tests\TestCase;

class PhoneServicesTest extends TestCase
{
    private $services;
    private $request;
    private $phone;
    private $phoneDb;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub;
        $this->services = new PhoneServices();
        $random = rand(1, 500);
        $this->request = [
            "number" => "980-504-41601" . $random . $random,
            "name" => "Miss Ivah Pacocha Sr."
        ];
        $this->phone = Phone::factory(1)->make();
        $this->phoneDb = Phone::all()->find(5);

    }

    public function testUpdateServices()
    {
        $this->services->update($this->phoneDb, $this->request);
        $this->assertTrue(true);
    }

    public function testSearchServices()
    {
        $this->services->delete($this->phone[0]);
        $this->assertTrue(true);
    }

    public function testDeleteServices()
    {
        $this->services->delete($this->phone[0]);
        $this->assertTrue(true);
    }
}
